In [1]:
import pandas as pd

In [2]:
dp02_data = pd.read_csv('ACS_16_5YR_DP02_with_ann.csv')

dp02_data.drop(['GEO.id','GEO.id2'], 1, inplace=True)
dp02_data.drop([col for col in dp02_data if col.startswith('HC02')], 1, inplace=True)
dp02_data.drop([col for col in dp02_data if col.startswith('HC04')], 1, inplace=True)
dp02_data.to_csv('dp02.csv', index=False)
dp02_data = pd.read_csv('dp02.csv', skiprows=1)
# dp02_data.head()

/home/tom/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2698: DtypeWarning: Columns (1,3,4,5,7,8,11,12,15,16,19,20,23,24,27,28,31,32,35,36,39,40,43,44,47,48,51,52,55,56,67,68,69,71,72,75,76,79,80,83,84,87,88,91,92,95,96,97,99,100,103,104,107,108,111,112,115,116,119,120,121,123,124,127,128,131,132,135,136,139,140,143,144,145,147,148,171,172,173,175,176,179,180,183,184,187,188,191,192,195,196,197,199,200,203,204,207,208,209,211,212,215,216,219,220,223,224,227,228,231,232,233,235,236,239,240,243,244,247,248,251,252,255,256,259,260,271,272,273,275,276,279,280,281,283,284,287,288,289,291,292,295,296,297,299,300,303,304,305,307,308,311,312,313,315,316,319,320,323,324,327,328,331,332,335,336,339,340,343,344,345,347,348,351,352,355,356,359,360,363,364,367,368,371,372,373,375,376,379,380,383,384,385,387,388,389,391,392,395,396,399,400,401,403,404,407,408,411,412,413,415,416,419,420,423,424,427,428,431,432,435,436,439,440,441,443,444,447,448,451,452,455,456,459,460,463,464,467,468,471,472,475,476,479,480,483,484,487,488,489,491,492,495,496,499,500,503,504,507,508,511,512,515,516,519,520,523,524,527,528,531,532,535,536,539,540,543,544,547,548,551,552,555,556,559,560,563,564,567,568,571,572,575,576,579,580,583,584,587,588,591,592,595,596) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)
/home/tom/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2698: DtypeWarning: Columns (71,72,73) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [3]:
dp03_data = pd.read_csv('ACS_16_5YR_DP03_with_ann.csv')

dp03_data.drop(['GEO.id','GEO.id2'], 1, inplace=True)
dp03_data.drop([col for col in dp03_data if col.startswith('HC02')], 1, inplace=True)
dp03_data.drop([col for col in dp03_data if col.startswith('HC04')], 1, inplace=True)
dp03_data.to_csv('dp03.csv', index=False)
dp03_data = pd.read_csv('dp03.csv', skiprows=1)
# dp03_data.head()

/home/tom/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2698: DtypeWarning: Columns (1,3,4,5,7,8,11,12,15,16,19,20,23,24,27,28,31,32,33,39,40,41,43,44,47,48,51,52,55,56,57,59,60,63,64,65,67,68,71,72,73,75,76,79,80,83,84,87,88,91,92,95,96,103,104,105,107,108,111,112,115,116,119,120,123,124,127,128,129,131,132,135,136,139,140,143,144,147,148,151,152,155,156,159,160,163,164,167,168,171,172,175,176,179,180,183,184,185,187,188,191,192,195,196,199,200,203,204,205,207,208,211,212,215,216,219,220,223,224,227,228,231,232,235,236,239,240,243,244,255,256,263,264,271,272,279,280,287,288,295,296,299,300,301,303,304,307,308,311,312,315,316,319,320,323,324,327,328,331,332,335,336,339,340,355,356,357,379,380,381,383,384,387,388,391,392,395,396,399,400,401,403,404,407,408,409,411,412,413,415,416,417,419,420,423,424,427,428,431,432,435,436,437,439,440,443,444,447,448,451,452,455,456,457,459,460,463,464,467,468,471,472) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [4]:
dp04_data = pd.read_csv('ACS_16_5YR_DP04_with_ann.csv')

dp04_data.drop(['GEO.id','GEO.id2'], 1, inplace=True)
dp04_data.drop([col for col in dp04_data if col.startswith('HC02')], 1, inplace=True)
dp04_data.drop([col for col in dp04_data if col.startswith('HC04')], 1, inplace=True)
dp04_data.to_csv('dp04.csv', index=False)
dp04_data = pd.read_csv('dp04.csv', skiprows=1)
# dp04_data.head()

/home/tom/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2698: DtypeWarning: Columns (1,3,4,5,7,8,11,12,23,24,25,27,28,31,32,35,36,39,40,43,44,47,48,51,52,55,56,59,60,63,64,65,67,68,71,72,75,76,79,80,83,84,87,88,91,92,95,96,99,100,103,104,107,108,109,111,112,115,116,119,120,123,124,127,128,131,132,135,136,139,140,143,144,151,152,153,155,156,159,160,163,164,167,168,171,172,175,176,179,180,181,183,184,187,188,199,200,201,203,204,207,208,211,212,215,216,219,220,223,224,227,228,229,231,232,235,236,239,240,243,244,247,248,249,251,252,255,256,259,260,263,264,267,268,271,272,275,276,279,280,283,284,287,288,289,291,292,295,296,299,300,303,304,305,307,308,311,312,315,316,319,320,321,323,324,327,328,331,332,335,336,339,340,343,344,347,348,351,352,359,360,361,363,364,367,368,371,372,373,375,376,379,380,383,384,387,388,391,392,395,396,399,400,407,408,409,411,412,415,416,419,420,423,424,427,428,431,432,439,440,441,443,444,447,448,451,452,455,456,459,460,463,464,467,468,469,471,472,475,476,479,480,483,484,487,488,491,492,495,496,499,500,503,504,505,507,508,511,512,515,516,519,520,523,524,527,528,531,532,539,540,543,544,545,547,548,551,552,555,556,559,560,563,564,567,568,571,572) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)
/home/tom/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2698: DtypeWarning: Columns (145,149) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [5]:
dp05_data = pd.read_csv('ACS_16_5YR_DP05_with_ann.csv')

dp05_data.drop(['GEO.id','GEO.id2'], 1, inplace=True)
dp05_data.drop([col for col in dp05_data if col.startswith('HC02')], 1, inplace=True)
dp05_data.drop([col for col in dp05_data if col.startswith('HC04')], 1, inplace=True)
dp05_data.to_csv('dp05.csv', index=False)
dp05_data = pd.read_csv('dp05.csv', skiprows=1)
# dp05_data.head()

/home/tom/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2698: DtypeWarning: Columns (1,3,4,5,7,8,11,12,15,16,19,20,23,24,27,28,31,32,35,36,39,40,43,44,47,48,51,52,55,56,59,60,63,64,71,72,75,76,79,80,83,84,87,88,89,91,92,95,96,99,100,101,103,104,107,108,111,112,113,115,116,119,120,123,124,127,128,131,132,135,136,139,140,143,144,147,148,151,152,155,156,159,160,163,164,167,168,171,172,175,176,179,180,183,184,187,188,191,192,195,196,199,200,203,204,207,208,211,212,215,216,219,220,223,224,227,228,231,232,233,235,236,239,240,243,244,247,248,251,252,255,256,259,260,261,263,264,267,268,271,272,275,276,279,280,283,284,287,288,291,292,295,296,299,300,303,304,307,308,311,312,315,316,319,320,323,324,327,328,329,331,332,335,336) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [6]:
dpall_data = pd.merge(dp02_data, dp03_data, on='Geography', how='outer')
del dp02_data, dp03_data
dpall_data = pd.merge(dpall_data, dp04_data, on='Geography', how='outer')
del dp04_data
dpall_data = pd.merge(dpall_data, dp05_data, on='Geography', how='outer')
del dp05_data
dpall_data.head()

,Geography,Estimate; HOUSEHOLDS BY TYPE - Total households,Percent; HOUSEHOLDS BY TYPE - Total households,Estimate; HOUSEHOLDS BY TYPE - Total households - Family households (families),Percent; HOUSEHOLDS BY TYPE - Total households - Family households (families),Estimate; HOUSEHOLDS BY TYPE - Total households - Family households (families) - With own children of the householder under 18 years,Percent; HOUSEHOLDS BY TYPE - Total households - Family households (families) - With own children of the householder under 18 years,Estimate; HOUSEHOLDS BY TYPE - Total households - Family households (families) - Married-couple family,Percent; HOUSEHOLDS BY TYPE - Total households - Family households (families) - Married-couple family,Estimate; HOUSEHOLDS BY TYPE - Total households - Family households (families) - Married-couple family - With own children of the householder under 18 years,...,"Estimate; HISPANIC OR LATINO AND RACE - Total population - Not Hispanic or Latino - Two or more races - Two races excluding Some other race, and Three or more races","Percent; HISPANIC OR LATINO AND RACE - Total population - Not Hispanic or Latino - Two or more races - Two races excluding Some other race, and Three or more races",Estimate; HISPANIC OR LATINO AND RACE - Total housing units,Percent; HISPANIC OR LATINO AND RACE - Total housing units,"Estimate; CITIZEN, VOTING AGE POPULATION - Citizen, 18 and over population","Percent; CITIZEN, VOTING AGE POPULATION - Citizen, 18 and over population","Estimate; CITIZEN, VOTING AGE POPULATION - Citizen, 18 and over population - Male","Percent; CITIZEN, VOTING AGE POPULATION - Citizen, 18 and over population - Male","Estimate; CITIZEN, VOTING AGE POPULATION - Citizen, 18 and over population - Female","Percent; CITIZEN, VOTING AGE POPULATION - Citizen, 18 and over population - Female"
0,ZCTA5 01001,7190.0,7190.0,3943.0,54.8,1406.0,19.6,3096.0,43.1,1017.0,...,101,0.6,7482,(X),13628,13628,6075,44.6,7553,55.4
1,ZCTA5 01002,9561.0,9561.0,4626.0,48.4,2068.0,21.6,3463.0,36.2,1352.0,...,679,2.3,10498,(X),23051,23051,10861,47.1,12190,52.9
2,ZCTA5 01003,26.0,26.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,226,2.0,26,(X),10612,10612,5372,50.6,5240,49.4
3,ZCTA5 01005,1840.0,1840.0,1150.0,62.5,462.0,25.1,962.0,52.3,344.0,...,5,0.1,2189,(X),4073,4073,2034,49.9,2039,50.1
4,ZCTA5 01007,5611.0,5611.0,4010.0,71.5,1882.0,33.5,3275.0,58.4,1462.0,...,380,2.6,5903,(X),10948,10948,5153,47.1,5795,52.9

In [7]:
dpall_data.to_csv('dpall.csv', index=False)

In [9]:
labelfile = open('columns.txt', 'w')
for item in list(dpall_data.columns.values):
    labelfile.write("%s\n" % item)

In [14]:
dpall_data['Geography']

0        ZCTA5 01001
1        ZCTA5 01002
2        ZCTA5 01003
3        ZCTA5 01005
4        ZCTA5 01007
5        ZCTA5 01008
6        ZCTA5 01009
7        ZCTA5 01010
8        ZCTA5 01011
9        ZCTA5 01012
10       ZCTA5 01013
11       ZCTA5 01020
12       ZCTA5 01022
13       ZCTA5 01026
14       ZCTA5 01027
15       ZCTA5 01028
16       ZCTA5 01029
17       ZCTA5 01030
18       ZCTA5 01031
19       ZCTA5 01032
20       ZCTA5 01033
21       ZCTA5 01034
22       ZCTA5 01035
23       ZCTA5 01036
24       ZCTA5 01037
25       ZCTA5 01038
26       ZCTA5 01039
27       ZCTA5 01040
28       ZCTA5 01050
29       ZCTA5 01053
            ...
33090    ZCTA5 00921
33091    ZCTA5 00923
33092    ZCTA5 00924
33093    ZCTA5 00925
33094    ZCTA5 00926
33095    ZCTA5 00927
33096    ZCTA5 00934
33097    ZCTA5 00936
33098    ZCTA5 00949
33099    ZCTA5 00950
33100    ZCTA5 00951
33101    ZCTA5 00952
33102    ZCTA5 00953
33103    ZCTA5 00956
33104    ZCTA5 00957
33105    ZCTA5 00959
33106    ZCTA5 00960
33107    ZCTA5 00961
33108    ZCTA5 00962
33109    ZCTA5 00965
33110    ZCTA5 00966
33111    ZCTA5 00968
33112    ZCTA5 00969
33113    ZCTA5 00971
33114    ZCTA5 00976
33115    ZCTA5 00979
33116    ZCTA5 00982
33117    ZCTA5 00983
33118    ZCTA5 00985
33119    ZCTA5 00987
Name: Geography, Length: 33120, dtype: object